server {
    listen 80;
    server_name _;

    root /var/www/public;
    index index.php index.html;

    client_max_body_size 40M;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Arquivos enviados pelo Laravel
    location ^~ /storage/ {
        alias /var/www/storage/app/public/;
        access_log off;
        expires 30d;
        add_header Cache-Control "public";
    }

    # Livewire
    location ^~ /livewire/ {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Arquivos estáticos
    location ~* \.(css|js|ico|png|jpg|jpeg|gif|svg|webp|woff|woff2|ttf|eot)$ {
        try_files $uri =404;
        expires 30d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    # PHP / Laravel
    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        fastcgi_read_timeout 300;
    }

    # Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Bloquear arquivos ocultos
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
